Feature/oc 153 header new design
OrdinaNederland/to-the-root pull request #67
Opened 2022-03-17 17:32 UTC by DrKlonk

Created a new header according to [this design](https://app.zeplin.io/project/622f05fbcbefb03b75e1f0ae/screen/622f3f811d99bf4c0d5dfcec).

It's probably still full of meh programming, I haven't really refactored much. No need to be gentle about it, but I wanted to get this out. And all in all, it seems to work fine.

The new way the profile icon should be used is described [here](https://one-community.atlassian.net/browse/OC-155) and is therefore not part of this PR.

2022-03-18 13:28 UTC, dennis-ordina commented on frontend/assets/scss/variables.scss
> +$header-height-mobile: 82px;
All those px 😱 hahaha

2022-03-18 13:31 UTC, dennis-ordina commented on frontend/components/layout/TheHeader.vue
> +        icon: 'explore',
You sure? 😜

2022-03-18 13:34 UTC, dennis-ordina commented on frontend/components/layout/TheHeader.vue
> +      & > .header__link {
Fancy 😎

2022-03-18 13:39 UTC, dennis-ordina commented on frontend/components/layout/TheLogo.vue
> +      required: false,
Als je een default value mee geeft hoef je required niet meer op false te zetten : https://v2.vuejs.org/v2/guide/components-props.html?redirect=true#Prop-Validation

2022-03-18 13:40 UTC, dennis-ordina approved these changes

2022-03-18 13:40 UTC, dennis-ordina commented
Niceee!

2022-03-18 13:44 UTC, dennis-ordina requested changes
Hij is alleen wel heeeeeel erg hoog op mijn laptopscherm. Mag van mij wel een heel stuk minder:
<img width="1440" alt="Screenshot 2022-03-18 at 14 43 22" src="https://user-images.githubusercontent.com/92443937/159013804-5b499991-392c-4e6d-91fa-9309c1d90a22.png">

2022-03-21 08:55 UTC, DrKlonk commented
> Hij is alleen wel heeeeeel erg hoog op mijn laptopscherm. Mag van mij wel een heel stuk minder: <img alt="Screenshot 2022-03-18 at 14 43 22" width="1440" src="https://user-images.githubusercontent.com/92443937/159013804-5b499991-392c-4e6d-91fa-9309c1d90a22.png">

Helemaal mee eens, ik vind m ook te hoog. Ik zal er een Jira issue voor aanmaken voor Francisca. Kunnen we er later naar kijken

2022-03-21 09:11 UTC, DrKlonk commented on frontend/assets/scss/variables.scss
> +$header-height-mobile: 82px;
Unfortunately I think we need them

2022-03-21 09:13 UTC, DrKlonk commented on frontend/components/layout/TheHeader.vue
> +        icon: 'explore',
🗺️

2022-03-21 09:27 UTC, dennis-ordina commented on frontend/assets/scss/variables.scss
> +$header-height-mobile: 82px;
Haha unfortunately I think so too

2022-03-21 09:30 UTC, dennis-ordina approved these changes

2022-03-21 13:26 UTC, merged